categories:
  - title: '🚀 Features'
    label: 'feature'
  - title: '🐛 Bug Fixes'
    label: 'fix'
  - title: '📚 Documentations'
    label: 'documentation'
  - title: '💩 Random'
    label: 'misc'
template: |
  ## What's Changed
  $CHANGES
