export const LOGIN_START = 'AUTH__LOGIN_START';
export const LOGIN_SUCCESS = 'AUTH__LOGIN_SUCCESS';
export const LOGIN_FAIL = 'AUTH__LOGIN_FAIL';

export const REGISTER_START = 'AUTH__REGISTER_START';
export const REGISTER_SUCCESS = 'AUTH__REGISTER_SUCCESS';
export const REGISTER_FAIL = 'AUTH__REGISTER_FAIL';

export const LOGOUT_START = 'AUTH__LOGOUT_START';
export const LOGOUT_SUCCESS = 'AUTH__LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'AUTH__LOGOUT_FAIL';
