export const FETCH_FRIENDS_PROGRESS = 'FETCH_FRIENDS_PROGRESS';
export const FETCH_FRIENDS_SUCCESS = 'FETCH_FRIENDS_SUCCESS';
export const FETCH_FRIENDS_ERROR = 'FETCH_FRIENDS_ERROR';

export const CHANGE_ACTIVE_FRIEND = 'CHANGE_ACTIVE_FRIEND';
